package com.tuxlogic.shiftiq.platform.iot.domain.model.aggregates;

import com.tuxlogic.shiftiq.platform.iot.domain.model.events.DtcAlertTriggeredEvent;
import com.tuxlogic.shiftiq.platform.iot.domain.model.valueobjects.DtcAlertId;
import com.tuxlogic.shiftiq.platform.iot.domain.model.valueobjects.DtcAlertSeverity;
import com.tuxlogic.shiftiq.platform.shared.domain.model.aggregates.AbstractDomainAggregateRoot;
import com.tuxlogic.shiftiq.platform.shared.domain.model.valueobjects.BranchId;
import lombok.Getter;

import java.time.Instant;
import java.util.UUID;

/**
 * Domain Aggregate Root representing a DTC Alert generated by a vehicle.
 */
@Getter
public class DtcAlert extends AbstractDomainAggregateRoot<DtcAlert> {

    private DtcAlertId id;
    private UUID telemetrySnapshotId;
    private BranchId branchId;
    private String dtcCode;
    private String description;
    private DtcAlertSeverity severity;
    private Instant createdAt;

    public DtcAlert() {
    }

    /**
     * Reconstitution constructor, used by the persistence assembler when
     * loading an existing alert. Does not raise domain events.
     */
    public DtcAlert(
            DtcAlertId id,
            UUID telemetrySnapshotId,
            BranchId branchId,
            String dtcCode,
            String description,
            DtcAlertSeverity severity,
            Instant createdAt
    ) {
        this.id = id;
        this.telemetrySnapshotId = telemetrySnapshotId;
        this.branchId = branchId;
        this.dtcCode = dtcCode;
        this.description = description;
        this.severity = severity;
        this.createdAt = createdAt != null ? createdAt : Instant.now();
    }

    /**
     * Creation constructor, used when a device reports a new DTC code during
     * telemetry ingestion. Raises {@link DtcAlertTriggeredEvent}.
     */
    public DtcAlert(
            UUID telemetrySnapshotId,
            BranchId branchId,
            String dtcCode,
            String description,
            DtcAlertSeverity severity
    ) {
        this(DtcAlertId.random(), telemetrySnapshotId, branchId, dtcCode, description, severity, Instant.now());
        registerDomainEvent(new DtcAlertTriggeredEvent(
                this.id.value(),
                this.branchId,
                this.telemetrySnapshotId,
                this.dtcCode,
                this.severity
        ));
    }
}