# Spring Application Name
spring.application.name=shiftiq-platform

# Database Configuration
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:shiftiq_db}
spring.datasource.username=${DATABASE_USER:shiftiq_user}
spring.datasource.password=${DATABASE_PASSWORD:shiftiq_password}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=com.tuxlogic.shiftiq.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=30

# Application Settings
app.frontend.url=https://atelier-webapp-11848.vercel.app

# Google OAuth Configuration
google.client.id=${GOOGLE_CLIENT_ID}

# Factos Integration
factos.api.url=${FACTOS_API_URL:https://factos-reva.onrender.com}
factos.api.key=${FACTOS_API_KEY:aa1e22c0ea1b41adbd1ce571542213bb}