ALTER TABLE customers ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500);
ALTER TABLE owners ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500);
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS photo_url VARCHAR(500);
